spring.application.name=eureka
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Prefer hostname in Docker (container name resolves correctly)
eureka.instance.prefer-ip-address=false
