# ===============================
# Application Info
# ===============================
spring.application.name=api-gateway
server.port=5051

# ===============================
# Eureka Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# ===============================
# JWT Configuration
# ===============================
jwt.secret=e34bdaaa694f33b3beb35ab79bb2f69061688ee1e94400c9605889e72cffe94

# ===============================
# Spring Cloud Gateway
# ===============================
# IMPORTANT: We use Java-based configuration in GatewayConfig.java
# So we DISABLE property-based routes to avoid conflicts
spring.cloud.gateway.discovery.locator.enabled=false

# ===============================
# Logging
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.alexZ.api_gatewayAlexz=DEBUG